---
ci_version: &ci_version "${CI_VERSION:-1.3}"
common_env_vars: &common_env_vars
  BUILD_TYPE: "GDK"
  GDK_BRANCH: "${GDK_BRANCH:-match_branch_name_pref::master}"
  PROJECT_BRANCH: "main_branch::${BUILDKITE_BRANCH}"
  USE_FASTBUILD: "${USE_FASTBUILD:-True}"
  IS_BUILDKITE_BUILD: "${IS_BUILDKITE_BUILD:-True}"
  BUILD_ANDROID: "${BUILD_ANDROID:-False}"
  SKIP_TESTS: "${SKIP_TESTS:-False}"
  CLEAN_BUILD: "${CLEAN_BUILD:-False}"
  SLOW_TESTS: "${SLOW_TESTS}"

steps:
  # Trigger a 4.26 build
  - trigger: "unrealgdkbuild-ci"
    label: "testgyms-ci-4.26"
    async: false
    build:
      branch: *ci_version
      message: "testgyms-4.26 ${BUILDKITE_MESSAGE}"
      env: 
        <<: *common_env_vars
        ENGINE_BRANCH: "${ENGINE_BRANCH_426:-match_branch_name_pref_engine::4.26-SpatialOSUnrealGDK}"
        ENGINE_MAJOR: "4.26"

  # Trigger a 4.25 build test
  - trigger: "unrealgdkbuild-ci"
    label: "testgyms-ci-4.25"
    async: false
    build: 
      branch: *ci_version
      message: "testgyms-4.25 ${BUILDKITE_MESSAGE}"
      env: 
        <<: *common_env_vars
        ENGINE_BRANCH: "${ENGINE_BRANCH_425:-match_branch_name_pref_engine::4.25-SpatialOSUnrealGDK}"
        ENGINE_MAJOR: "4.25"
