---
ci_version: &ci_version "${CI_VERSION:-main}"
common_env_vars: &common_env_vars
  BUILD_TYPE: "GDK"
  GDK_BRANCH: "${GDK_BRANCH:-match_branch_name_pref::master}"
  PROJECT_BRANCH: "main_branch::${BUILDKITE_BRANCH}"
  USE_FASTBUILD: "${USE_FASTBUILD:-True}"
  IS_BUILDKITE_BUILD: "${IS_BUILDKITE_BUILD:-True}"
  BUILD_ANDROID: "${BUILD_ANDROID:-False}"
  CLEAN_BUILD: "${CLEAN_BUILD:-False}"
  RUN_DEFAULT_TESTS: "${RUN_DEFAULT_TESTS:-True}"
  SLOW_TESTS: "${SLOW_TESTS:-False}"
  EXTRA_TESTS: "${EXTRA_TESTS:-}"
  EXTRA_TESTS_RUN_NATIVE: "${EXTRA_TESTS_RUN_NATIVE:-False}"
  EXTRA_TESTS_RUN_REPGRAPH: "${EXTRA_TESTS_RUN_REPGRAPH:-False}"
  EXTRA_TESTS_RUNS: "${EXTRA_TESTS_RUNS:-1}"
  ENGINE_UNITY_MODE: "${ENGINE_UNITY_MODE:-True}"
  GDK_UNITY_MODE: "${GDK_UNITY_MODE:-False}"
  ENGINE_USE_PCH: "${ENGINE_USE_PCH:-True}"

steps:
  # Trigger a 4.27 build
  - trigger: "unrealgdkbuild-ci"
    label: "testgyms-ci-4.27"
    async: false
    build:
      branch: *ci_version
      message: "testgyms-4.27 ${BUILDKITE_MESSAGE}"
      env: 
        <<: *common_env_vars
        ENGINE_BRANCH: "${ENGINE_BRANCH_427:-match_branch_name_pref_engine::4.27-SpatialOSUnrealGDK}"
        ENGINE_MAJOR: "4.27"

  # Trigger a 4.26 build
  - trigger: "unrealgdkbuild-ci"
    label: "testgyms-ci-4.26"
    async: false
    build: 
      branch: *ci_version
      message: "testgyms-4.26 ${BUILDKITE_MESSAGE}"
      env: 
        <<: *common_env_vars
        ENGINE_BRANCH: "${ENGINE_BRANCH_426:-match_branch_name_pref_engine::4.26-SpatialOSUnrealGDK}"
        ENGINE_MAJOR: "4.26"
