---
ci_version: &ci_version "1.1"

# This is designed to trap and retry failures because agent lost
# connection. Agent exits with -1 in this case.
agent_transients: &agent_transients
  exit_status: -1
  limit: 3

# BK system error
bk_system_error: &bk_system_error
  exit_status: 255
  limit: 3

# job was interrupted by a signal (e.g. ctrl+c etc)
bk_interrupted_by_signal: &bk_interrupted_by_signal
  exit_status: 15
  limit: 3

# Hook failure
bk_hook_failure: &bk_hook_failure
  exit_status: 127
  limit: 3

steps:
  # New build pipeline
  # Trigger a 4.26 build
  - trigger: "unrealgdkbuild-ci"
    label: "testgyms-ci-4.26"
    async: false
    build:
      branch: *ci_version
      message: "testgyms-4.26 ${BUILDKITE_MESSAGE}"
      env: 
        BUILD_TYPE: "GDK"
        GDK_BRANCH: "${GDK_BRANCH:-0.13.0}" # NOTE: temp fix for new ci release interop issues
        ENGINE_BRANCH: "${ENGINE_BRANCH:-4.26-SpatialOSUnrealGDK-0.13.0}" # NOTE: temp fix for new ci release interop issues
        ENGINE_MAJOR: "4.26"
        PROJECT_BRANCH: "${BUILDKITE_BRANCH}"
        USE_FASTBUILD: "True"
        IS_BUILDKITE_BUILD: "True"
        BUILD_ANDROID: "False"
        SKIP_TESTS: "False"
        CLEAN_BUILD: "False"

  # Trigger a 4.25 build
  - trigger: "unrealgdkbuild-ci"
    label: "testgyms-ci-4.25"
    async: false
    build: 
      branch: *ci_version
      message: "testgyms-4.25 ${BUILDKITE_MESSAGE}"
      env: 
        BUILD_TYPE: "GDK"
        GDK_BRANCH: "${GDK_BRANCH:-0.13.0}" # NOTE: temp fix for new ci release interop issues
        ENGINE_BRANCH: "${ENGINE_BRANCH:-4.25-SpatialOSUnrealGDK-0.13.0}" # NOTE: temp fix for new ci release interop issues
        ENGINE_MAJOR: "4.25"
        PROJECT_BRANCH: "${BUILDKITE_BRANCH}" # NOTE: temp fix for new ci release interop issues
        USE_FASTBUILD: "True"
        IS_BUILDKITE_BUILD: "True"
        BUILD_ANDROID: "False"
        SKIP_TESTS: "False"
        CLEAN_BUILD: "False"
